version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aspri_db
      POSTGRES_USER: aspri_user
      POSTGRES_PASSWORD: aspri_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aspri_user -d aspri_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://aspri_user:aspri_password@db:5432/aspri_db
      SECRET_KEY: your-secret-key-change-in-production
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data: