"""Add pending_action to chat_sessions

Revision ID: f1b2c3d4e5f6
Revises: ebe41baa2682
Create Date: 2025-08-10 19:48:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b2c3d4e5f6'
down_revision = 'ebe41baa2682'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('pending_action', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'pending_action')
    # ### end Alembic commands ###
